
#pragma once

enum TokenType {
		LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE,
		LEFT_BRACKET, RIGHT_BRACKET, COMMA, DOT, SEMICOLON, 
		QUESTION, COLON,

		BANG, BANG_EQUAL, EQUAL, EQUAL_EQUAL, GREATER,
		GREATER_EQUAL, LESS, LESS_EQUAL, MINUS, MINUS_EQUAL, PLUS,
		PLUS_EQUAL, SLASH, SLASH_EQUAL, STAR, STAR_EQUAL, ARROW,

		IDENTIFIER, STRING, NUMBER,

		AND, CLASS, CONST, ELSE, FALSE, FUNC, FOR, IF, NIL, OR, PRINT,
		RETURN, SUPER, THIS, TRUE, VAR, WHILE, REPEAT, MEMBER,
		METHOD, CONSTRUCTOR, CHAIN, WITH, BREAK,

		END_OF_FILE
};